name: Deploy Production

on:
  push:
    branches:
      - "main"

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DIRECT_URL: ${{ secrets.DIRECT_URL }}

jobs:
  deploy-production:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: |
            - args: [--frozen-lockfile]

      - name: Run Prisma Migrate
        run: |
          pnpm run db:generate
          pnpm run db:migrate
